# Site settings
title: "yuhao's map"
description: 'a firmware engineer.<br>Let the dream come true !!'
url: 'https://yuhao-kuo.github.io'
baseurl: ''
profilepic: 'https://yuhao-kuo.github.io/images/me260.jpg'
bkimage: '/images/background.jpg'
google_analytics: UA-136518943-1
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Kuo, Yu-Hao'
  email: yuhao.kaku@gmail.com
  github_username:  yuhao-kuo
  linkedin_username:  yuhao-kuo

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
